name: base_bloc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  email_validator: ^2.0.1
  google_fonts: ^2.1.0
  flutter_dotenv: ^5.0.0
  flutter_svg: ^0.22.0
  pull_to_refresh: ^2.0.0
  logger: ^1.0.0
  event_bus: ^2.0.0
  get_storage: ^2.0.2  # save data to storage(sharePref)
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.0
  fluttertoast: ^8.0.9
  flutter_bloc: ^8.1.1
  #  device_info_plus: ^2.0.1
  device_info: ^2.0.3
  expandable_page_view: ^1.0.14
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.3.0
  connectivity_plus: ^2.3.0 #internet connection
  sqflite: ^2.0.2+1
  back_button_interceptor: ^6.0.1
  equatable: ^2.0.5
  dio: ^4.0.6
  fluro: ^2.0.3
  visibility_detector: ^0.3.3
  get_it: ^7.2.0
  badges: ^2.0.3
  like_button: ^2.0.4
  video_thumbnail: ^0.5.2
  video_player: ^2.4.4
  wakelock: ^0.6.1+2
  flutter_tags: ^1.0.0-nullsafety.1
  rxdart: ^0.27.5
  google_maps_flutter: ^2.1.12
  zoom_widget: ^2.0.0
  flutter_speed_dial: ^6.0.0
  permission_handler: ^10.1.0
  weekly_date_picker: ^1.3.0
  babylonjs_viewer: ^1.1.0
  dropdown_button2:
    git:
      url: git@github.com:NguyenXuanLoc/dropdown_button2.git
      ref: master
  flutter_blue_elves: ^0.1.9
  geolocator: ^9.0.2
  location: ^4.4.0

  flutter_staggered_grid_view: ^0.6.2


dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0 #
flutter:
  generate: true # Add this line
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/td/
flutter_icons:
  android: "launcher"
  ios: true
  image_path: "assets/png/logoapp.png"
  min_sdk_android: 21
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
